hotkey:
  app-name: hotkey-demo
  etcd-server: http://127.0.0.1:2379  # etcd服务器地址，集群用逗号分隔，这里使用本地
  caffeine-size: 50000                # 设置本地缓存最大数量，默认5万
  push-period: 200                      #  批量推送key的间隔时间，默认500ms，该值越小，上报热key越频繁，相应越及时，建议根据实际情况调整
  #  如单机每秒qps10个，那么0.5秒上报一次即可，否则是空跑。该值最小为1，即1ms上报一次。

spring:
  application:
    name: ${name:springboot-hotkey-demo}
  ###############################---redis---##############################
  redis:
    host: ${REDIS_HOST:47.106.155.227}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}

server:
  port: 9090